#pragma config(Motor,  port2,           fleftdrive,    tmotorVex393_HBridge, openLoop, encoderPort, None)
#pragma config(Motor,  port3,           bleftdrive,    tmotorVex393_HBridge, openLoop, encoderPort, None)
#pragma config(Motor,  port8,           frightdrive,   tmotorVex393_HBridge, openLoop, encoderPort, None)
#pragma config(Motor,  port9,           brightdrive,   tmotorVex393_HBridge, openLoop, encoderPort, None)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{motor[fleftdrive] = 0;
		motor[bleftdrive] = 0;
		motor[frightdrive] = 0;
		motor[brightdrive] = 0;
	while(true)
	{
		motor[fleftdrive] = vexRT[Ch3];
		motor[bleftdrive] = -vexRT[Ch3];// made it reverse to move forward(in the same direction) with the other wheels
		motor[frightdrive] = vexRT[Ch2];
		motor[brightdrive] = -vexRT[Ch2];// made it reverse to move forward(in the same direction) with the other wheels
	}

}
